services:
  - type: web
    name: dev-toolkit-presentation
    runtime: static
    plan: free
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
